version: 2
updates:
  # Enable version updates for our CI github-actions.
  - package-ecosystem: "github-actions"
    # For GitHub Actions, setting the directory to / will check for workflow
    # files in .github/workflows.
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    # The following is required for workspaces to be updated: see https://github.com/dependabot/dependabot-core/issues/5226.
    versioning-strategy: increase
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typedoc-plugin-markdown"
        update-types: ["version-update:semver-major"]
    groups:
      internal-tooling:
        patterns:
          - "@inrupt/internal-*"
          - "@inrupt/base-*"
          - "@inrupt/jest-*"
          - "@inrupt/eslint-*"
      external-types:
        patterns:
          - "@types/*"
  - package-ecosystem: "pip"
    directory: "/packages/browser/docs/api"
    schedule:
      interval: "weekly"
