name: Audit

on:
  push:
  schedule:
    - cron: "40 10 * * *"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm audit --audit-level=moderate
      # We can't just run `lerna exec "npm audit"`, because that would fail when
      # preparing a new version: when the versions are bumped, but not published
      # yet, `npm audit` would fail.
      - run: npm run audit-all -- --no-fix
      - name: Send a notification that the audit has failed
        if: failure() && github.event_name == 'schedule'
        run: "curl -X POST -H Content-type: 'application/json' --data \"{\\\"text\\\":\\\"Automated npm audit --audit-level=moderate failed. View <https://github.com/inrupt/solid-client-js/actions/runs/$RUN_ID|the execution log> for more details.\\\"}\" $WEBHOOK_E2E_FAILURE"
        env:
          WEBHOOK_E2E_FAILURE: "${{ secrets.WEBHOOK_E2E_FAILURE }}"
          RUN_ID: "${{ github.run_id }}"
